name: Full Stack Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install backend
      - name: Install backend
        working-directory: ./backend
        run: npm ci

      # Start backend
      - name: Start backend
        working-directory: ./backend
        run: |
          nohup npm start > backend.log 2>&1 &
          echo $! > backend.pid
        env:
          NODE_ENV: test
          PORT: 3001

      # Install frontend
      - name: Install frontend
        working-directory: ./frontend
        run: npm ci

      # Start frontend
      - name: Start frontend
        working-directory: ./frontend
        run: |
          nohup npm start > frontend.log 2>&1 &
          echo $! > frontend.pid
        env:
          BROWSER: none

      # Configure Playwright
      - name: Configure Playwright
        working-directory: ./frontend
        run: |
          echo "import { defineConfig } from '@playwright/test';

          export default defineConfig({
            webServer: {
              command: 'npm start',
              url: 'http://localhost:3000',
              reuseExistingServer: !process.env.CI,
              timeout: 120 * 1000
            },
            use: {
              baseURL: 'http://localhost:3000',
            }
          });" > playwright.config.ts

      # Run tests
      - name: Run UI tests
        working-directory: ./frontend
        run: |
          npx playwright install --with-deps
          npx playwright test

      - name: Debug logs
      if: always()
      run: |
        echo "=== Frontend Log ==="
        cat frontend/frontend.log || true
        echo "=== Backend Log ==="
        cat backend/backend.log || true
