name: Full Stack Tests
on: [push, pull_request]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install backend dependencies and start server
      - name: Setup Backend
        working-directory: ./backend
        run: |
          npm ci
          npm start &
        env:
          NODE_ENV: test
          PORT: 3001

      # Install frontend dependencies and start server
      - name: Setup Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm start &

      # Wait for servers
      - name: Wait for servers
        run: |
          echo "Waiting for servers to start..."
          sleep 10
          echo "Checking servers..."
          curl --retry 5 --retry-delay 3 http://localhost:3000 || echo "Frontend not ready"
          curl --retry 5 --retry-delay 3 http://localhost:3001 || echo "Backend not ready"

      # Run Playwright tests
      - name: Run UI Tests
        working-directory: ./frontend
        run: |
          npx playwright install --with-deps
          npx playwright test

      # Run Postman tests
      - name: Run API Tests
        working-directory: ./backend
        run: |
          npm install -g newman
          newman run postman_api_testing/collection/Todo_APIs.json \
            -e postman_api_testing/Environment/Todo_Env.json \
            -r cli,html \
            --reporter-html-export api-results.html

      # Upload reports
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: postman-results
          path: backend/api-results.html
